server:
  port: 8888
  context-path: /
spring:
  datasource:
    url: jdbc:mysql://10.10.100.254:3306/ntask?useUnicode=true&characterEncoding=utf8
    username: ntask
    password: dev
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update